### ISSUE TITLE
Problem executing indexer.js

### ISSUE THREAD

**Issue by kilfoy** [MaxBittker/StaticIndexer#2]
I am trying to execute indexer.js and getting the following error. Any ideas?

C:\Users\abcd\Desktop\SimManager\2016>node indexer.js
C:\Users\abcd\Desktop\SimManager\2016\indexer.js:12
function cleanup(str, stripCommas = 0) {
                                  ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

**Comment by MaxBittker** [comment]
Try updating your version of node, stripCommas = 0 is a default argument syntax that was added to the language some time in the last year or 2. Hope this helps

**Comment by michael-milette** [comment]
Hi Kilfoy, when I recently used indexer.js, I was unable to get it to work from the Windows CMD command prompt because it does not include an _npm_ command which is used to install Cheerios.js properly (you did install it, right?). In the end, I ended up running it under Cygwin where it worked perfectly. Hope this helps.

Best regards,
Michael
